version: "3.9"

services:
  web-server:
    build: .
    command: npm run dev
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=remotemysql.com
      - DB_USER=EXalnYXJ4m
      - DB_PASSWORD=QhuLsEwcFF
      - DB_NAME=EXalnYXJ4m